packages/istanbul-lib-instrument/src/source-coverage.js
addresses https://github.com/istanbuljs/babel-plugin-istanbul/issues/99
=> fix: loc is sometimes not defined, so loc.start throw exception

packages/istanbul-reports/lib/json-summary/index.js
Copied from https://github.com/istanbuljs-archived-repos/istanbul-reports/pull/20
=> fix(windows): preserve escape char of json-summary key path

packages/istanbul-lib-instrument/src/instrumenter.js
add support for jsx syntax, flow annotations, async generators and dynamic imports
=> feat: extend babilon support

packages/istanbul-lib-coverage/lib/coverage-map.js, packages/test-exclude/index.js
As discussed, previous changes redone in the mono-repo and introduced a parameter/flag in stead of a separate module.
The problem I try to resolve:
I've a 'non-standard' setup, where I build my distribution-packages outside of the source folder. I do this because I write mainly ES6 code, and distribution-packages need to be plain old JavaScript. In addition because AVA is perfectly able to run ES6 tests, but not able to test ES6 modules I've to transpile my ES6 code (using rollup and babel/bublé) to plain JavaScript. The resulting transpiled file will also include all libraries being `import`ed.
The indication source files and line missing coverage works perfectly, using sourcemaps. However in the sourcemaps the original full paths are included. So if I run `nyc` with an include or …
=> Add possibility to filter coverage maps on absolute filename

packages/istanbul-lib-source-maps/README.md, packages/istanbul-lib-source-maps/lib/map-store.js, packages/istanbul-lib-source-maps/lib/transformer.js, packages/istanbul-lib-source-maps/package.json
based on @ben-eb's suggestion, switch to using `debug` module, rather than spitting out messages to `stdout`.
fixes #27
=> feat: pull in debug module, to make debug messages optional

packages/istanbul-lib-coverage/lib/file.js, packages/istanbul-lib-coverage/test/file.test.js
#42 
This branchMap structure is used by both the Cobertura and  the Clover reporters. A fix would add accurate conditional coverage to both.
=> istanbuljs/istanbuljs#42 - Add failing test for Cobertura reporter branchMap structure

packages/istanbul-lib-report/lib/file-writer.js, packages/istanbul-reports/lib/text/index.js, packages/istanbul-reports/package.json, packages/istanbul-reports/test/fixtures/specs/100-line-100-branch.json, packages/istanbul-reports/test/fixtures/specs/100-line-missing-branch.json, packages/istanbul-reports/test/fixtures/specs/missing-line-missing-branch.json, packages/istanbul-reports/test/text/index.js
Implement @isaacs suggestion in #41, we will now show missing branches once 100% line coverage is reached:
fixes #41
=> feat: once 100% line coverage is achieved, missing branch coverage is now shown in text report

packages/istanbul-api/package.json, packages/istanbul-lib-coverage/package.json, packages/istanbul-lib-hook/package.json, packages/istanbul-lib-instrument/package.json, packages/istanbul-lib-report/package.json, packages/istanbul-lib-source-maps/package.json, packages/istanbul-reports/package.json, packages/test-exclude/package.json
All the urls should be refered to this repo that
can be easily found from npm.
Git url, bug url and homepage have been changed in package.json
=> chore: update repo url

packages/istanbul-lib-instrument/src/visitor.js, packages/istanbul-lib-instrument/test/specs/classes.yaml, packages/istanbul-lib-instrument/test/util/guards.js
With `const foo = class {}`, `foo.name` should be `'foo'`. Without this commit the instrumentation causes `foo.name` to be an empty string.
Hoist the statement counter just like it's done for function and arrow expressions. Fixes #59.
=> fix: hoist statement counter for class variables

packages/test-exclude/index.js, packages/test-exclude/test/test-exclude.js
@davewasmer  how does this look? very much appreciate the failing tests 👍
=> fix: add more general support for negated exclude rules

.gitignore, packages/istanbul-lib-instrument/api.md, packages/istanbul-lib-instrument/package.json, packages/istanbul-lib-instrument/test/specs.test.js, packages/istanbul-lib-instrument/test/specs/switch.yaml
I've tracked the issue @isaacs is running into to [this change](https://github.com/babel/babylon/issues/574) in Babylon.
There's one other [ignore related issue](https://github.com/istanbuljs/nyc/issues/595) I'd like to also add a regression test for, at which point I'd think downgrading babylon might be a good temporary fix.
=> chore: add failing test for #64

packages/istanbul-lib-instrument/src/visitor.js
https://github.com/babel/babel/pull/5940 is a breaking change that fixes a bug, so making the change now since I hit it when trying to update in preset-env
https://github.com/babel/babel-preset-env/pull/372
=> update to use correct node type

packages/istanbul-api/lib/file-matcher.js
It will make glob run faster.
---
- before:
> fileset 7 files 7769ms
- after:
> fileset 7 files 27ms
=> fix: set excludes to options.ignore on fileset

packages/istanbul-reports/lib/html/annotator.js, packages/istanbul-reports/test/fixtures/github-80a.json, packages/istanbul-reports/test/fixtures/github-80b.json, packages/istanbul-reports/test/fixtures/github-80c.json, packages/istanbul-reports/test/html/annotator.js
With the logic in place, seems like `startLine` will always == `endLine`
so the condition will never be `false`. Coupled with the fact that
the original `endCol` from the `meta` object seems wrong (always less
than `startCol`), the hightlighting just went to the end of the file.
~~Fix this by removing the redundant logic and always setting the
`endCol` to the end of line using `text.originalLength()`~~
Fix this by removing the redundant logic and setting the
`endCol` to the end of line using `text.originalLength()` when
the given `endCol` is less than `startCol`
=> fix: branch highlighting was going to end of file for HTML reports

.travis.yml, package.json, packages/istanbul-lib-instrument/package.json, packages/istanbul-lib-instrument/src/instrumenter.js, packages/istanbul-lib-instrument/test/specs/object-spread.yaml, packages/istanbul-lib-instrument/test/util/guards.js, yarn.lock
adds support for object spread syntax:
```
const a = {a: 99}
const b = {b: 33}
const c = {...a, ...b}
console.log(c)
> {a: 99, b: 33}
```
fixes https://github.com/istanbuljs/nyc/issues/657
=> feat: add support for object-spread syntax

packages/istanbul-lib-source-maps/package.json
Due to https://nodesecurity.io/advisories/534
It's a major version bump, but looking at the changelog I don't
see any breaking changes of note.
=> deps: upgrade debug package

packages/istanbul-lib-report/lib/file-writer.js
When `FileWriter` is used to get a `ConsoleWriter` (such as in the text report), the call to `mkdirp.sync()` in the constructor creates a directory that is never used. `FileWriter#copyFile()` and `FileWriter#writeFile()` already call `mkdirp.sync()` before writing files, so the call in the constructor isn't needed anyway.
=> Remove call to mkdirp.sync() in FileWriter constructor

packages/istanbul-lib-instrument/src/visitor.js, packages/istanbul-lib-instrument/test/specs.test.js, packages/istanbul-lib-instrument/test/specs/ignore.yaml, packages/istanbul-lib-instrument/test/util/verifier.js
Sometimes in my projects I'll have one or two files that I don't want to have coverage for. It's annoying to have to edit the config to just ignore one or two files (especially if that config is hidden away in another tool).
This PR adds a feature for ignoring entire files by allowing you to add a comment: `/* istanbul ignore file */` and it will skip instrumenting the entire file.
To do this, I create another regex especially for this full file ignore, then in the program enter and exit visitor, we check whether the parent of the program node (the file node) has any comments which match this regex. If it does, then we'll skip doing any instrumentation.
This PR also tests this functionality with a new `specs/ignore.yaml`. It requires adding a new option called `noCoverage` which functions …
=> feat: add support for ignoring entire files

packages/istanbul-lib-instrument/src/visitor.js, packages/istanbul-lib-instrument/test/specs/classes.yaml, packages/istanbul-lib-instrument/test/varia.test.js
prior to the regression in `1.9` it looks like we didn't add line counters to functions or classes. It seems like we should eventually do this, but there are a bunch of caveats around this that we need to address -- related to exports vs. non exports, etc.
This rolls back any attempt to instrument classes for line coverage at this time.
fixes #110
=> fix: address issue with class instrumentation

packages/istanbul-lib-instrument/src/instrumenter.js, packages/istanbul-lib-instrument/test/index.test.js, packages/istanbul-lib-instrument/test/varia.test.js
I noticed that passing preserveComments: false to Istanbul doesn't do anything. Comments were never removed. I fixed this. The option was simply never used anywhere. Also wrote a test for it and fixed one other test
Hope my changes are OK, otherwise please let me know!
=> Fixes proper passing of the preserveComments option to babel

packages/istanbul-lib-instrument/src/visitor.js, packages/istanbul-lib-instrument/test/specs/functions.yaml
Hi, it’s been a while! 👋 Hope y’all are doing great!
This patch makes the code a little more robust by not assuming that the instrumented code contains no function named `Function`.
=> fix: fix instrumentation when a function is called Function

packages/istanbul-lib-instrument/src/read-coverage.js, packages/istanbul-lib-instrument/src/visitor.js
Babel 7 does not return program scope from getFunctionParent().
This fix also still works with babel 6
https://github.com/babel/babel/pull/5923
=> Fix compatibility with babel 7

packages/test-exclude/index.js, packages/test-exclude/test/test-exclude.js
- exclude test folder inside each package in a monorepo
- exclude -test.js suffix
=> resolves #132 add additional patterns to default excludes

packages/istanbul-api/lib/config.js, packages/istanbul-lib-instrument/api.md, packages/istanbul-lib-instrument/src/instrumenter.js, packages/istanbul-lib-instrument/src/visitor.js, packages/istanbul-lib-instrument/test/specs/statement-hints.yaml
Currently there is no general way to ignore all class methods with a certain name. It has been problematic when writing code for a project that always has a trivial method to be required to ignore it on each class.
This allows a global ignore of all methods of a certain name.
As this is my first pull request, please let me know if there are any special processes to follow.
Thank you!
=> Allow ignoring class methods

packages/istanbul-reports/index.js
Hi,
This is my attempt to add custom reporters support to nyc:
I tried to do this as seamless and in the least obtrusive way possible in order to just make use of the `--reporter=<reporter-name>` flag in nyc.
I just want to start the ball rolling here, if you have any other idea on how to acomplish this I would be glad to roll up my sleeves and help out here.
Also made a custom reporter that is working with these changes and is working great for my use case:
https://github.com/pedrocarrico/istanbul-reporter-aws-cloudwatch-metrics
It's still a proof of concept but soon I'll add more features and tests to it.
Also linking https://github.com/istanbuljs/nyc/issues/387 here.
Many thanks,
=> Load custom reporters

packages/istanbul-lib-instrument/src/visitor.js, packages/istanbul-lib-instrument/test/varia.test.js
Parenthesizing every superClass node will render `extendsNative` in `babel-plugin-transform-classess` useless. As we can see from the [code](https://github.com/babel/babel/blob/e2c5f25e97757cf4f7bd1527c51a9b61a29115ac/packages/babel-plugin-transform-classes/src/transformClass.js#L669), the transformer relies on a static superClass name to apply `wrapNativeSuper` helper. For example, it will transpile
```js
class MyError extends Error {
constructor() {
super("hey");
}
}
```
into
```js
var MyError =
/*#__PURE__*/
function (_Error) {
_inherits(MyError, _Error);
function MyError() {
_classCallCheck(this, MyError);
return _possibleConstructorReturn(this, (MyError.__proto__ || Object.getPrototypeOf(MyError)).call(this, "hey"));
}
return MyError;
}(_wrapNativeSuper(Error));
```
Here is a living …
=> fix: parenthesize superClass on non-idetifier case

packages/istanbul-reports/lib/text/index.js
https://github.com/istanbuljs/istanbuljs/issues/169
Looking forward to feedback on this. 
Let me know if this is a change you'd be interested in taking, and I can work on adding test coverage.
=> ability to skip rows with full coverage

packages/istanbul-lib-hook/lib/hook.js
BREAKING CHANGE: the closure provied to hookRequire, hookRunInThisContext, etc., is now passed an object with a filename member, rather than a string representing filename.
=> fix: 1.2.x should have been a breaking change

packages/test-exclude/package.json
The only breaking change is that we dropped support for Node.js 4, which shouldn't affect this module since it seems like it only supports Node.js 6 and up.
=> test-exclude: bump read-pkg-up dependency

packages/istanbul-lib-instrument/src/visitor.js, packages/istanbul-lib-instrument/test/specs/object-method.yaml
nyc currently reports the following code as containing 0 functions.  Add
ObjectMethod visitor to istanbul-lib-instrument so these are seen.
```js
const obj = {
get prop() { return 0; }
fn() {}
*gen() {}
};
```
=> fix: Instrument ObjectMethod's.

packages/istanbul-lib-instrument/src/visitor.js
src/visitor.js contains the logic to skip files containing comments
matching 'istanbul ignore file'.  Unfortunately the comment for the
patter contained this exact word, blocking coverage from our own test.
Rewrite the comment so the file is not ignored.
=> fix: Don't ignore src/visitor.js for self test.

packages/nyc-config-babel/README.md, packages/nyc-config-babel/index.json, packages/nyc-config-babel/package.json
BREAKING CHANGE: This updated configuration requires babel-plugin-istanbul 5.0.0.
Now requires node >=6 per dependencies.
=> feature: Update for babel 7.

packages/istanbul-reports/package.json
BREAKING CHANGE: Requires node >= 6.
=> chore: Specify node >= 6 in istanbul-reports.

packages/istanbul-lib-instrument/src/index.js, packages/istanbul-lib-instrument/src/instrumenter.js, packages/istanbul-lib-instrument/test/plugins.test.js
This PR introduces:
The ability to add more plugins for `@babel/parser`
- adds the option `plugins`
- unit test
=> Add option plugins

packages/istanbul-reports/lib/clover/index.js
fix: clover report metrics must be an inline xml element see https://bitbucket.org/atlassian/clover/src/default/etc/schema/clover.xsd (#13)
=> fix: clover report metrics must be an inline xml element (#13)

packages/istanbul-lib-source-maps/lib/transformer.js, packages/istanbul-lib-source-maps/test/map-store.test.js
This pulls in @loganfsmyth's modifications to the remapping algorithm for SourceMaps.
I have a couple questions that I've left inline, please note that the tests that need to be modified reference the following:
```js
// Original source
// export class SimpleClass {
//     hy() {
//         console.log("Hy");
//     }
// }
// Transpiled Source
// "use strict";
// var SimpleClass = (function () {
//     function SimpleClass() {
//     }
//     SimpleClass.prototype.hy = function () {
//         console.log("Hy");
//     };
//     return SimpleClass;
// }());
// exports.SimpleClass = SimpleClass;
```
CC: @loganfsmyth, @SimenB
=>  fix: pull in @loganfsmyth's SourceMap fixes

packages/istanbul-lib-source-maps/lib/transformer.js
A linter should probably have caught this
=> fix: correct variable name in source-map transform

packages/istanbul-reports/lib/lcovonly/index.js
Replace `Object.keys(functions)` by `Object.keys(functionMap)` since inside of the loop `functionMap[key]` is used for lookup.
This is also the same behaviour as for the `cobertura` reporter here: https://github.com/istanbuljs/istanbuljs/blob/2857f990a85c9f276ec96f0e6969a33577be4ea7/packages/istanbul-reports/lib/cobertura/index.js#L98-L109
`Object.keys(fnMap)` is used for iteration and then `fnMap[k].decl.start.line` is used for accessing the data.
see: https://github.com/istanbuljs/istanbuljs/issues/224
=> bug fix for #224: failed to write coverage report (lcovonly)

packages/istanbul-lib-report/lib/summarizer.js, packages/istanbul-lib-report/test/summarizer.test.js
This fixes an issue I was experiencing when using the nested summarizer and the coverage map had no files.
Previously it would throw an error
```
TypeError: other.contains is not a function
at Path.ancestorOf (/Users/heatherroberts/Desktop/Test Projects/jest/node_modules/istanbul-lib-report/lib/path.js:97:18)
```
=> Fix for nested strategy when no files

packages/istanbul-reports/lib/html/assets/block-navigation.js
When looking at the file listing view of an HTML code coverage report, allow the usual keyboard shortcuts to cycle through low coverage metrics (highlighting the particular statement/branch/lines etc. cell that has low coverage).
This change is most useful for code coverage reports with hundreds or thousands of files in a listing.  Similar to how just tapping `n` is useful for jumping to the first issue in a large code file, being able to tap `n` and jump to the first file with low/missing coverage might also be helpful.
(Functionally, it's probably just as easy and more flexible to click Sort on the file column header, but this is an easy change and seems consistent.)
No unit tests changed or added.  Tested locally in Chrome, Firefox and Safari.
=> Suggestion: Enable keyboard shortcuts on HTML report file listing view

.prettierignore
Something we forgot in #261 was to make sure our automated tools (semantic-version etc) don't get messed with by prettier on release
=> chore: prettierignore files modified on release

packages/istanbul-lib-instrument/api.md, packages/istanbul-lib-instrument/src/instrumenter.js, packages/istanbul-lib-instrument/src/visitor.js, packages/istanbul-lib-instrument/test/varia.test.js
This new option allows modification of the function which finds the
global variable scope.  The default global scope is `this`, resulting in
`(new Function('return this))()` to retrieve the global scope.  This can
now be changed, for example `window.top` could be used to always use the
top level IFRAME in a web browser.
Fixes #199
=> feat: New option coverageGlobalScope.

package.json, packages/istanbul-api/package.json, packages/istanbul-lib-coverage/package.json, packages/istanbul-lib-hook/package.json, packages/istanbul-lib-instrument/package.json, packages/istanbul-lib-report/package.json, packages/istanbul-lib-source-maps/package.json, packages/istanbul-reports/package.json, packages/nyc-config-babel/package.json, packages/nyc-config-typescript/package.json, packages/test-exclude/package.json
`npm home istanbul-lib-instrument` should open https://istanbul.js.org/.
`npm home` from the lerna root should open
https://github.com/istanbuljs/istanbuljs.
=> chore: Update homepage link in package.json files.

packages/istanbul-lib-instrument/src/visitor.js, packages/istanbul-lib-instrument/test/varia.test.js
=> fix: Honor istanbul ignore next hints placed before export statement.

packages/istanbul-lib-source-maps/lib/transformer.js, packages/istanbul-lib-source-maps/test/transformer.test.js
The paths "/path/to/file.js" and "\path\to\file.js" points to the same file on Windows, this PR makes `istanbuljs` treat them as one file by using `_path_to_file.js` as a key internally when transforming coverage maps.
Long story short, this makes `istanbuljs` behave well without reporting duplicates, regardless of input.
=> Map unique files once, regardless of path separator

.travis.yml, packages/test-exclude/index.js, packages/test-exclude/test/fixtures/subprocess/bin/subprocess.js, packages/test-exclude/test/fixtures/subprocess/package.json, packages/test-exclude/test/test-exclude.js
* Use node.js 6 features
* Expand test coverage to 100%
---
Next step will be to add support for `getAllFiles` so we can centralize some more of the include/exclude logic here.
=> chore: ES2015ify test-exclude.

packages/istanbul-reports/lib/html/assets/base.css
As discussed in https://github.com/gotwarlost/istanbul/issues/542, this
PR brings back the yellow colour for medium.
There are many good points raised in that PR, and this PR, aims to
replicate address those concerns for this repo.
=> feat: set medium colour to yellow

package-lock.json, package.json, packages/istanbul-api/package-lock.json, packages/istanbul-lib-instrument/package-lock.json, packages/istanbul-lib-report/package-lock.json, packages/istanbul-lib-source-maps/package-lock.json, packages/test-exclude/package-lock.json
`highlight.js@9.15.x` fails to install so add a devDependency on ~9.14.2
to prevent any attempt to install the broken version.  This is not
directly needed by istanbul but is used by documentation.
=> chore: Pin highlight.js to ~9.14.2 to avoid install error.

packages/test-exclude/index.js, packages/test-exclude/test/test-exclude.js
This PR is the first step at resolving [NYC's issue #898](https://github.com/istanbuljs/nyc/issues/898) I raised. The idea is to be able to turn off the default exclusion of `**/node_modules/**` for users that need/want to support local `node_modules`. As mentioned in that issue, the `negateExclude` (i.e. `!**/node_modules/**`) doesn't work for cases when you still want your exclusion list to still exclude matches within your local `node_modules` directory. 
Related PRs for solving the above issue:
- https://github.com/istanbuljs/nyc/pull/912
- https://github.com/istanbuljs/babel-plugin-istanbul/pull/172
**NOTE:** Not sure if you also would want the `exportFunc.defaultExclude` list to take into account this option. For now, I'm not touching that so for this flag to work, at least one …
=> Support turning off node_modules default exclude via flag

.travis.yml
This is needed until we can figure out what is going on with node.js 11.11.0.
=> chore: Block node 11.11.0 from CI

packages/istanbul-lib-report/lib/file-writer.js, packages/istanbul-lib-report/test/file-writer.test.js
This meant that the sort indicator arrows were broken (on windows 10 chrome anyway)
=> fix copy of arrow png on html report

greenkeeper.json
This (hopefully) configures greenkeeper to report updates for the actual
packages.  This will also enable testing of in-range upates.
The ignore list is modules that require node.js 8, we won't be dropping
node.js 6 until nyc@15.
=> chore: Add greenkeeper.json configuration.

package-lock.json, package.json, packages/istanbul-api/package-lock.json, packages/istanbul-api/package.json, packages/istanbul-lib-hook/package-lock.json, packages/istanbul-lib-instrument/package-lock.json, packages/istanbul-lib-report/package-lock.json, packages/istanbul-lib-source-maps/package-lock.json, packages/istanbul-reports/package-lock.json, packages/test-exclude/package-lock.json
Npm audit reports security vulnerability on js-yaml < 3.13.0
=> chore: Upgrade js-yaml to 3.13.0

packages/test-exclude/index.js, packages/test-exclude/test/test-exclude.js
This is appended to the `exclude` list unless excludeNodeModules is
disabled.  Removing from the default list makes it easier to use
excludeNodeModules as you no longer need to reset the `exclude` array to
get coverage of node_modules.
Fixes #347
=> fix: Remove `**/node_modules/**` from defaultExclude.

packages/istanbul-lib-instrument/src/visitor.js, packages/istanbul-lib-instrument/test/util/verifier.js, packages/istanbul-lib-instrument/test/varia.test.js
ts-node gets angry when coverageData.hash is set after coverageData is
declared, add it to the initial object instead of setting it separately.
Fixes #336
---
Note for the instrumentation to be error-free with ts-node requires getting rid of the `var Function = (function(){}).constructor;`.  I know this was added for a reason, I don't want to create an explosion of new options.  So for now the `istanbul-lib-instrument` answer is to set the following options:
```js
{
coverageGlobalScopeFunc: false,
coverageGlobalScope: '(new Function("return this"))()'
}
```
I believe using these options would produce ts-node compatible code.  Unfortunately these options are not exposed by nyc or babel-plugin-istanbul.
=> fix: Be more friendly to ts-node.

packages/istanbul-lib-instrument/src/instrumenter.js
This allows code with these features to be instrumented without having
to reconfigure the parser plugins.
Fixes #338
=> feat: Add bigInt and importMeta to default parser plugins.

packages/istanbul-reports/lib/html/assets/sorter.js
https://github.com/istanbuljs/istanbuljs/pull/289 broke sorting as it removed the assignment to `cols` which is referenced later on
https://github.com/istanbuljs/istanbuljs/blob/9dac4c6fe63e089f0296f17ba295e64d02b3334d/packages/istanbul-reports/lib/html/assets/sorter.js#L61
In a web browser loading the html report gives the following in the web console:
```console
TypeError: cols is undefined[Learn More] sorter.js:62:13
loadRowData https://coverage.nodejs.org/coverage-09cdc3782488d2e6/sorter.js:62
loadData https://coverage.nodejs.org/coverage-09cdc3782488d2e6/sorter.js:77
addSorting https://coverage.nodejs.org/coverage-09cdc3782488d2e6/sorter.js:164
```
cc @Trott
=> fix sorting

packages/istanbul-reports/lib/html/index.js
This is the only change required to allow https://github.com/istanbuljs/istanbuljs/pull/345 - because that uses the existing report to generate the file nodes, which include a breadcrumb.. so it overrides the report breadcrumb function.
I thought I would modernize it to a class at the same time, since thats whats been suggested of the classes in #345
=> Make the html report into a class and allow the breadcrumb to be overridden

packages/istanbul-lib-source-maps/lib/get-mapping.js
I'm running into issues adding source-map support to c8, in which `LEAST_UPPER_BOUND` returns `mapping.source === null`.
If I loosen up our check so that it falls back to the default behavior of `GREATEST_LOWER_BOUND` in this edge-case, c8's remapping works like a charm, see:
----
@loganfsmyth can you clarify for me why this change might address my issues? I understand that they underlying cause is most likely that V8's coverage ranges don't directly map to the mappings generated by TypeScript ... but why would `LEAST_UPPER_BOUND` be returning `null`? 
Reading the documentation, shouldn't it simply return the next closest element that's a greater line number than the element I'm remapping -- I guess I don't fully understand the scenarios that result in `LEAST_UPPER_BOUND` or …
=> fix: if LEAST_UPPER_BOUND returns null, try GREATEST_LOWER_BOUND

packages/istanbul-reports/lib/cobertura/index.js
This issue has been hanging out for a long while and seems to have effected a lot of other people. I thought I had discovered a fix by just ensuring my source files were not all in one directory but then the  problem popped up again.
I could not discover a good reason why this check exists, more specifically why it exists only for these tags. In fact, all it seems to do is break the report format when its generated, which means its no good for the Jenkins API :(
This bug has blocked my work several times now so I figured I'd try contributing the fix.
=> fix(istanbul-reports): Remove isRoot check causing incorrect report formatting (#66).

packages/istanbul-reports/lib/cobertura/index.js
Reverts istanbuljs/istanbuljs#382
=> Revert "fix(istanbul-reports): Remove isRoot check causing incorrect report formatting (#66)."

packages/istanbul-lib-report/lib/summarizer.js, packages/istanbul-lib-report/test/summarizer.test.js
the nested summarizer nicely combines directories in this scenario
```
file
lib1/sub/file
```
(e.g. you don't see lib1 and lib1/sub differently)
but in this scenario
```
lib1/sub/file
lib1/sub2/file
```
you don't get to see `lib1` and children `sub` and `sub2` but instead get two entries in the root.. unless there is a file inside `lib1` root.
This makes the report look quite weird and inconsistent when you have certain structures e.g.
```
app/file
app/sub1/file
app/sub2/file
mods/sub1/file
mods/sub2/file
```
here you see
```
app
file
sub1
file
sub2
file
mods/sub1
file
mods/sub2
file
```
This fixes it. The existing implemnation was imo a bit of a hack - mutating the package transform and my first attempts to just "fix it" just made it worse, so I re-implemented it.
=> Fix the nested summarizer to combine directories

packages/test-exclude/index.js, packages/test-exclude/test/test-exclude.js
When `--experimental-modules` flag is enabled, those extensions are used to specify whether the script is CommonJS or ES module explicitly. https://nodejs.org/api/esm.html
=> fix: Also ignore *.cjs, *.mjs and .*ts by default

packages/istanbul-lib-report/lib/file-writer.js, packages/istanbul-lib-report/lib/path.js, packages/istanbul-lib-report/lib/summarizer.js, packages/istanbul-lib-report/lib/tree.js, packages/istanbul-lib-report/test/tree.test.js
* Drop "abstract" functions
* Rename Node and Tree to BaseNode and BaseTree
* Create ReportNode.createRoot static method
* Replace treeFor with ReportTree class
* Simplify multiple internal `summarizer.js` functions
* Implement getRoot in BaseTree
Ref #390
---
Will be additional follow-up but this is likely the last of the non-breaking changes for istanbul-lib-report.
CC @lukeapage
=> chore: Internal refactoring of istanbul-lib-report

packages/istanbul-api/README.md
BREAKING CHANGE: The istanbul-api module is now deprecated.  Any modules
which use istanbul-api should migrate.
Fixes #321
=> fix: Deprecate istanbul-api.

packages/test-exclude/default-exclude.js, packages/test-exclude/index.js, packages/test-exclude/package.json
This allows documentation to provide a permanent link to the master
version of the default exclude list.
---
CC @JaKXz once we do this we can update the nyc readme to just point to the default-exclude.js file.
=> chore: Move default excludes to stand-alone file

monorepo-merge-reports.js, monorepo-per-package-nycrc.json, package.json, packages/istanbul-lib-coverage/package.json, packages/istanbul-lib-hook/package.json, packages/istanbul-lib-instrument/package.json, packages/istanbul-lib-report/package.json, packages/istanbul-lib-source-maps/package.json, packages/istanbul-reports/package.json, packages/nyc-config-hook-run-in-this-context/package.json, packages/test-exclude/package.json
Test coverage should only count if we're directly testing the result of
something.  This runs nyc per package then produces combined reporting.
---
This effectively drops coverage from istanbul-api because I want to avoid any further commits to that package (other than deleting it).  This commit was part of #396 but I want to push it ahead.
This causes the reported coverage to drop significantly but this is more valid.
=> chore: Isolate coverage reporting per package

packages/istanbul-lib-report/index.js, packages/istanbul-lib-report/lib/context.js, packages/istanbul-lib-report/test/context.test.js
This was done as part of breaking API changes I'm making in istanbul-lib-report, decided to pull this out as a separate PR for easy review.  This is itself a non-breaking change as lib/context.js is not a public interface.
=> chore: Export class from lib/context.js

packages/test-exclude/default-exclude.js, packages/test-exclude/test/test-exclude.js
I often use the name `tests` rather than `test` when the directory contains multiple test files.
=> feat: ignore files under test"s" directories by default

packages/istanbul-lib-report/index.js, packages/istanbul-lib-report/lib/context.js, packages/istanbul-lib-report/lib/report-base.js, packages/istanbul-lib-report/lib/summarizer-factory.js, packages/istanbul-lib-report/test/context.test.js, packages/istanbul-lib-report/test/helpers/coverage-map.js, packages/istanbul-lib-report/test/index.test.js, packages/istanbul-lib-report/test/summarizer-factory.test.js, packages/istanbul-reports/lib/clover/index.js, packages/istanbul-reports/lib/cobertura/index.js, packages/istanbul-reports/lib/html-spa/index.js, packages/istanbul-reports/lib/html/index.js, packages/istanbul-reports/lib/json-summary/index.js, packages/istanbul-reports/lib/json/index.js, packages/istanbul-reports/lib/lcov/index.js, packages/istanbul-reports/lib/lcovonly/index.js, packages/istanbul-reports/lib/none/index.js, packages/istanbul-reports/lib/teamcity/index.js, packages/istanbul-reports/lib/text-lcov/index.js, packages/istanbul-reports/lib/text-summary/index.js, packages/istanbul-reports/lib/text/index.js, packages/istanbul-reports/test/cobertura-regression.js, packages/istanbul-reports/test/html-spa/index.js, packages/istanbul-reports/test/text/index.js
BREAKING CHANGE: This changes existing istanbul-lib-report API's.
Fixes #390
---
This is still WIP.  I feel like maybe istanbul-lib-report needs to define a base class for all reports to use, something which takes in options including a `defaultSummarizer` option.  The final API might be something where you create the reporting context, then for each report call `report.execute(context)`.  In this case the `execute` function would be defined in the base report class but could be overridden by specific reports (`html-spa` maybe?).
CC @lukeapage
=> feat!: Refactor istanbul-lib-report so report can choose summarizer

packages/test-exclude/index.js, packages/test-exclude/is-outside-dir-posix.js, packages/test-exclude/is-outside-dir-win32.js, packages/test-exclude/is-outside-dir.js, packages/test-exclude/nyc.config.js, packages/test-exclude/package.json, packages/test-exclude/test/test-exclude.js
=> fix(win32): Detect files on different drive as outside project

packages/test-exclude/nyc.config.js
PR is just so I can have travis run on Windows to verify 100% coverage.
=> chore: Enforce complete coverage for test-exclude

packages/istanbul-reports/lib/text-lcov/index.js
Encountered this error in early testing of nyc against alpha release.  Note that setting `file: '-'` after `...opts` is intentional, the whole point of the text-lcov report is that it writes to stdout.  If a user wants the `opts.file` to be respected they need to use the `lcov-only` report.
=> fix: Set `opts.file = '-'` on text-lcov

monorepo-merge-reports.js
On windows, the default `npm test` doesn't work for me.. investigating I see no documentation that spawn sync works with running a command installed in a sub node_modules.
I'm not 100% sue, I just know that master doesn't work for me.
This issue was informative: https://github.com/nodejs/node/issues/8077
=> Allow merge to work consistently on windows

packages/istanbul-reports/lib/html-spa/index.js
As previously discussed, this overrides the default summarizer so html-spa is always nested.
=> Force html-spa to always be nested

monorepo-merge-reports.js
@coreyfarrell you left some comments on my merged PR: https://github.com/istanbuljs/istanbuljs/pull/429
1. Your right, the path join isn't needed. I must have added it first and the shell: true afterwards and not tried removing the original attempt
2. The command doesn't actually fail - I am not sure why but on windows it ends up with succeeding but with 0 coverage. If we look at a travis build on windows just before my pr was merged:
https://travis-ci.org/istanbuljs/istanbuljs/jobs/549497029
you'll see
```
> istanbuljs@2.0.0 posttest C:\Users\travis\build\istanbuljs\istanbuljs
> node ./monorepo-merge-reports.js && nyc report
lerna success exec Executed command in 10 packages: "npm test"
null
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts …
```
=> Simplify the merge command

monorepo-per-package-full.js, packages/istanbul-lib-hook/package.json, packages/istanbul-lib-hook/test/hook.test.js, packages/test-exclude/nyc.config.js
monorepo-per-package-full.js and changes to packages/test-exclude/nyc.config.js are also in #452.  Since these changes are identical I think the second PR to be merged should just drop those changes.  If not I'll fix the merge conflict.
=> chore: full test coverage for istanbul-lib-hook

packages/istanbul-lib-coverage/lib/file-coverage.js, packages/istanbul-lib-coverage/test/file.test.js
Frequently users run `nyc --all` in a way that causes source files to be
transpiled for actual testing but not transpiled for `--all`.  This
produces incompatible coverage data and inconsistantly wrong reporting.
The work around here is to drop coverage produced by `--all` for any
file where we have coverage produced by actual test runs.  This ensures
that we prefer code that was transpiled in the way which tests actually
ran.
Fixes #123, #224, #260, #322, #413
=> fix: Drop unneeded coverage data from `nyc --all`

packages/istanbul-reports/lib/html/index.js
Documentation:
https://nodejs.org/api/path.html#path_windows_vs_posix
https://nodejs.org/api/path.html#path_path_posix
Fixes #195
Tested this locally and it works great.
=> Use path.posix.relative to fix paths when generating html reports on Windows

packages/istanbul-lib-instrument/src/visitor.js, packages/istanbul-lib-instrument/test/specs/if-hints.yaml
Fixes #468
---
~Note that the hint must be placed between the `else` and the `if` for this to work.  We should probably mention this at https://github.com/istanbuljs/nyc/#parsing-hints-ignoring-lines~ Looks like I was wrong, it works to put the hint before or after the `else`.  Test updated to prove it.
=> fix: Honor ignore hints in chained if statements

packages/istanbul-reports/lib/html-spa/index.js, packages/istanbul-reports/lib/html-spa/src/summaryTableLine.js, packages/istanbul-reports/test/fixtures/specs/maxcols.json
I've been discussing some things with @tisgro who is much better at ui/ux than me (he is working on a PR to make html-spa much prettier) and we came to some conclusions about a few elements of the report.
Firstly - when you have a file with multiple lines and no branches - it might be 0% covered, but because branches is 0/0 it is shown green - this is pretty misleading as you might be led to thinking nothing needs to be done on that file. The empty class is only used on each individual metric when all the metrics are empty. So this changes that, so each metric can be empty and if its empty, its shown white - basically ignore me.
Secondly - the colour applied to the filename comes from the statements - which isn't even an included metric! even if it was lines, its confusing because filters …
=> html-spa: Use empty per metric and make the overall the worst of all metrics

packages/istanbul-lib-source-maps/lib/map-store.js, packages/istanbul-lib-source-maps/lib/transformer.js
This is in support of restricting the amount of code nyc needs in the
synchronous path.
=> feat: Add addInputSourceMapsSync and getSourceMapSync methods

packages/istanbul-lib-instrument/src/visitor.js, packages/istanbul-lib-instrument/test/varia.test.js
This replaces the coverage variable with a function that returns
coverage data.
Fixes #92
=> fix: Eliminate babel hoisting of the coverage variable

packages/istanbul-lib-instrument/src/read-coverage.js
Matching the constructor fails if multiple copies of @babel/parser are
installed.
=> chore: Relax the check for ast in readInitialCoverage

packages/istanbul-lib-source-maps/lib/map-store.js, packages/istanbul-lib-source-maps/lib/transformer.js, packages/istanbul-lib-source-maps/test/map-store.test.js, packages/istanbul-lib-source-maps/test/transformer.test.js
BREAKING CHANGE: MapStore#transformCoverage is now async and returns a
the coverage data only.  The `sourceFinder` method is now async and
provided directly on the `MapStore` instance.
---
CC @SimenB I know you use this API in jest, any objections?  We're not yet upgrading to `source-map@0.7.x` but this will make that upgrade possible without further changes to the public API.  Moving the `sourceFinder` method from the result of transformCoverage to the class itself is not strictly needed but just seems correct.
=> feat: Convert to async API

packages/istanbul-reports/index.js, packages/istanbul-reports/package.json
=> fix: Add missing dependency on istanbul-lib-report

packages/istanbul-lib-instrument/package.json, packages/istanbul-lib-instrument/src/instrumenter.js, packages/istanbul-lib-instrument/src/read-coverage.js, packages/istanbul-lib-instrument/test/already-instrumented.test.js, packages/istanbul-lib-instrument/test/plugins.test.js, packages/istanbul-lib-instrument/test/specs/input-source-map.yaml
Further research is needed before this can be merged.  I think nyc does source-map merging after the fact.  Need to evaluate https://github.com/babel/babel/issues/10518, compare to current results when nyc does it's own source-map merging.
=> fix: Produce properly merged source-maps when inputSourceMap is provided

packages/istanbul-lib-source-maps/lib/transformer.js
When testing both original and transpiled sources it was possible for
mappedCoverage to be a FileCoverage instance when it needed to be a
MappedCoverage instance.
Fixes istanbuljs/nyc#940
=> fix: mappedCoverage.addStatement is not a function

packages/istanbul-lib-source-maps/lib/map-store.js
This function needs to be passed to report context constructors.
BREAKING CHANGE: `MapStore#sourceFinder` is no longer async
=> fix: sourceFinder cannot be async.

packages/nyc-config-typescript/index.js, packages/nyc-config-typescript/package.json
BREAKING CHANGE: This configuration is no longer valid for nyc 14 and
below.
---
@JaKXz do you agree that this is a breaking change?  Sorry I didn't catch this before releasing 1.0.0.
=> fix: Update to support nyc 15.

packages/istanbul-lib-instrument/src/visitor.js, packages/istanbul-lib-instrument/test/varia.test.js
Ensure that sources initialize coverage data even if no code is run.
---
The primary use case for this is ES modules that are not transpiled to CJS.  For example create fn1.js:
```js
export function fn1() {
console.log('test');
}
```
And index.js:
```js
import {fn1} from './fn1.js';
if (false) {
fn1();
}
```
The expected result is for `fn1.js` to be reported as zero coverage but since the file has code but does not execute any top-level code it never gets in this test case.
=> fix: Always call coverage initialization function

packages/istanbul-reports/lib/cobertura/index.js
see: https://github.com/bcoe/c8/issues/149
Fixes #527
Closes #528
=> fix: cobertura should escape invalid characters

packages/istanbul-lib-instrument/src/visitor.js
=> fix: Add ts-ignore to reassignment of generated function

packages/istanbul-lib-instrument/src/read-coverage.js
=> fix: Prevent readInitialCoverage from reading babel config

packages/nyc-config-typescript/README.md
It took me a long time to figure out how to use nyc with TypeScript without using Mocha – it ended up being fairly simple, but there's a lot that you can do wrong and no guidance in the documentation. Thought it may be useful to amend the documentation with the solution.
I also added a cautionary note about excluding the TypeScript compiled output directory.
=> Added instructions for using nyc-config-typescript with Jasmine

packages/istanbul-reports/lib/html-spa/assets/spa.css, packages/istanbul-reports/lib/html-spa/index.js, packages/istanbul-reports/lib/html-spa/src/summaryTableHeader.js, packages/istanbul-reports/lib/html-spa/src/summaryTableLine.js, packages/istanbul-reports/test/fixtures/specs/100-line-100-branch.json, packages/istanbul-reports/test/fixtures/specs/100-line-missing-branch.json, packages/istanbul-reports/test/fixtures/specs/coalescence.json, packages/istanbul-reports/test/fixtures/specs/empty-file-skip-empty.json, packages/istanbul-reports/test/fixtures/specs/empty-file.json, packages/istanbul-reports/test/fixtures/specs/maxcols.json, packages/istanbul-reports/test/fixtures/specs/missing-line-missing-branch.json, packages/istanbul-reports/test/html-spa/src/getChildData.js
Fixes #579 
Happy to change this to an option, but I do find it by far the most useful way to sort coverage data, since it tells you exactly where your biggest gaps are. As the issue mentions, this is the default sort order in some other coverage visualization tools.
=> Add "missed" column to html-spa report

packages/istanbul-lib-instrument/src/visitor.js
The body of this case clause duplicates the body of this case clause.
=> Remove duplicate code

packages/istanbul-lib-coverage/lib/percent.js, packages/istanbul-lib-coverage/test/percent.test.js, packages/istanbul-reports/test/fixtures/specs/100-line-missing-branch.json, packages/istanbul-reports/test/fixtures/specs/missing-line-missing-branch.json
Increase precision when calculating percentages to fix of by one errors when dealing with large numbers.
=> Fixes #593, increase precision when calculating percentages

packages/istanbul-reports/lib/text/index.js
This allows API users to pass a `summarizer` option to the text report.
=> feat: Honor summarizer for text report

packages/istanbul-lib-instrument/package.json, packages/istanbul-lib-instrument/src/visitor.js
The else statement in an if ... else statement is not correct. 
Input code:
`if (x) {
output = x;
}
else {
output = false;
}`
Problem output:
`branchMap: ..."1": {
"loc": {
"start": {
"line": 7,
"column": 2
},
"end": {
"line": 12,
"column": 3
}
},
"type": "if",
"locations": [{
"start": {
"line": 7,
"column": 2
},
"end": {
"line": 12,
"column": 3
}
}, {
"start": {
"line": 7, // PROBLEM
"column": 2
},
"end": {
"line": 12,
"column": 3
}
}
],
"line": 7
}`
Expected output:
`branchMap: ..."1": {
"loc": {
"start": {
"line": 7,
"column": 2
},
"end": {
"line": 12,
"column": 3
}
},
"type": "if",
"locations": [{
"start": {
"line": 7,
"column": 2
},
"end": {
"line": 12,
"column": 3
}
}, {
"start": {
"line": 10, // CORRECT
"column": 7
},
"end": {
"line": 12,
"column": 3
}
}
],
"line": 7
}`
Caveats: …
=> Fix coverage.branchMap else location.

packages/istanbul-lib-instrument/api.md, packages/istanbul-lib-instrument/src/instrumenter.js
When studying [`vite-plugin-istanbul`](https://github.com/iFaxity/vite-plugin-istanbul) and comparing it to [istanbul-lib-instrument/api.md](https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-lib-instrument/api.md), I saw that [it is passing `coverageGlobalScope` and `coverageGlobalScopeFunc` to `createInstrumenter`](https://github.com/iFaxity/vite-plugin-istanbul/blob/5265ed28068e8cff2b40dc51c1fe281fdaab381a/src/index.ts#L66-L68). 
The API docs do not mention these on instrumenter options. These are only mentioned on Program visitor API. 
Instrumenter is passing these to visitor through its options:
https://github.com/istanbuljs/istanbuljs/blob/7cea3b1b8916499398538be32aacf7c1181ef379/packages/istanbul-lib-instrument/src/instrumenter.js#L29-L34 …
=> docs: add missing `coverageGlobalScope` to instumenter API

packages/istanbul-lib-instrument/package.json, packages/nyc-config-hook-run-in-this-context/package.json
BREAKING CHANGE: minimum Node version bumped to 10.
=> fix(deps)!: upgrade semver CVE-2022-25883

packages/istanbul-reports/lib/clover/index.js
- update the clover reporter to close whatever tag is left open from before, rather than the explicit `package` tag. 
Close #715
=> fix(clover): always close last open tag

packages/istanbul-reports/lib/clover/index.js
The `projectRoot` option is not used by Clover reporter. 
The Clover schema specifies following for the `path` attribute so I guess it has to be full path, instead of relative like `projectRoot` is.
> `@path` - the filesystem-specific original path to the file e.g. c:\path\to\Bar.groovy
https://bitbucket.org/atlassian/clover/src/master/etc/schema/clover.xsd
=> refactor(istanbul-reports): remove unused `projectRoot` option from clover

packages/istanbul-lib-coverage/lib/file-coverage.js, packages/istanbul-lib-coverage/test/file.test.js
Fix: https://github.com/istanbuljs/v8-to-istanbul/issues/233
=> fix: merge ranges properly when contained by other ranges in set

packages/istanbul-lib-coverage/lib/file-coverage.js, packages/istanbul-lib-coverage/test/file.test.js
=> fix: do not throw on missing range locations

packages/istanbul-reports/lib/html/index.js
Fixes #730.
Best practices [discourage the use of inline event handlers](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#inline_event_handlers_%E2%80%94_dont_use_these), but beyond this it seems to cause an issue specific to Firefox's event handling mechanism.
In the current filtering code, two were events are added, one [in the setup function](https://github.com/istanbuljs/istanbuljs/commit/eab47f76be90343f679ef0e5567a21447a4995dc#diff-f32bbb8e6d8d5c271ebc689ab16169ef747e77fb80184746d7337a4827e5a94eR47) and the other [in the inline HTML](https://github.com/istanbuljs/istanbuljs/commit/eab47f76be90343f679ef0e5567a21447a4995dc#diff-f32bbb8e6d8d5c271ebc689ab16169ef747e77fb80184746d7337a4827e5a94eR47). The former is the actual desired filtering function, and …
=> fix(ux): address bug with firefox event handling

packages/istanbul-lib-source-maps/lib/get-mapping.js
Seems #685 accidentally reverted the change to use `allGeneratedPositionsFor` #768. The tests still pass, but but this is still a more correct implementation.
=> Redo: Use allGeneratedPositionsFor for more accurate source map transforms

.github/workflows/ci.yml, .github/workflows/release-please.yml
We're getting deprecation warnings.
Should also fix the error probably 🤔
=> chore: update GH Actions

.github/workflows/release-please.yml
Seems #769 broke the automated release somehow
https://github.com/istanbuljs/istanbuljs/actions/runs/8054774858/job/22000625358
No idea how... Maybe this fixes it? closer to the example in https://github.com/google-github-actions/release-please-action#release-types-supported
=> chore: maybe fix release

packages/istanbul-lib-instrument/api.md, packages/istanbul-lib-instrument/src/instrumenter.js, packages/istanbul-lib-instrument/test/generator-opts.test.js
`istanbul-lib-instrument` [allows](https://github.com/istanbuljs/istanbuljs/blob/main/packages/istanbul-lib-instrument/api.md#parameters-1) passing a set of Babel parser plugins, but I ran into an error when trying to use Istanbul with [Vitest](https://vitest.dev/) (more context at [this issue](https://github.com/vitest-dev/vitest/issues/5537)) after enabling the `"importAttributes"` plugin added in Babel v7.22.0 ([Babel docs](https://babeljs.io/docs/babel-parser#ecmascript-proposals)):
```
You are using import attributes, without specifying the desired output syntax.
Please specify the "importAttributesKeyword" generator option, whose value can be one of:
- "with"        : `import { a } from "b" with { type: "json" };`
- "assert"      : `import { a } from "b" assert { type: "json" };`
- …
```
=> fix: allow use of importAttributes Babel parser plugin

packages/istanbul-lib-source-maps/lib/transformer.js, packages/istanbul-lib-source-maps/test/testdata/ifWithImplicitElseCoverageData.json, packages/istanbul-lib-source-maps/test/transformer.test.js
- Fixes #705 
Tested the fix with reproduction case from downstream (https://github.com/vitest-dev/vitest/issues/2239) by modifying `./node_modules/istanbul-lib-source-maps/lib/transformer.js` on the fly. 
```
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |     100 |       50 |     100 |     100 |                   
cov.js   |     100 |       50 |     100 |     100 | 2                 
----------|---------|----------|---------|---------|-------------------
```
=> fix: `istanbul-lib-source-maps` to preserve implicit `else` when sourcemaps are used

packages/istanbul-lib-source-maps/lib/transformer.js, packages/istanbul-lib-source-maps/test/testdata/implicitElseEdgeCase.json, packages/istanbul-lib-source-maps/test/transformer.test.js
- Fixes https://github.com/istanbuljs/istanbuljs/pull/706#issuecomment-2200012354
In Vitest codebase the `istanbul-lib-source-maps@5.0.5` caused a crash in edge case. The crash happend when `swc` transpiled code was added to report as uncovered file (`coverage.all`).
We can safely look for `source` before adding implicit `else` into the map. There should always be `source` already set from the previous loop of the `if` itself.
=> fix: `istanbul-lib-source-maps` implicit `else` crash edge case
