packages/istanbul-lib-instrument/src/source-coverage.js
Lands #5 
Thanks for the contribution @nowycheung, landed here because I created a pretty brutal merge conflict polishing off the monorepo structure.
=> feat: add line numbers back to coverage.json

packages/istanbul-lib-instrument/test/specs/jsx.yaml
adds test for https://github.com/istanbuljs/istanbuljs/pull/22
@jonathanargentiero, @Axbon, your work is now landed in `istanbul-lib-instrument@1.7.0` would love your help testing it 👍
=> chore: add test for jsx syntax parsing

package.json, yarn.lock
=> chore(package): explicitly update nyc to v10.2.0

packages/istanbul-api/test/file-matcher.test.js
Extremely minor potential improvement... 
Closes https://github.com/istanbuljs-archived-repos/istanbul-api/pull/20
=> tests(istanbul-api): use before for expensive test op

packages/istanbul-lib-instrument/src/visitor.js
@MartinDawson I believe I have hunted down the underlying issue to an interaction between [babel-plugin-istanbul, and babel-plugin-rewire](https://github.com/speedskater/babel-plugin-rewire/issues/187)
I think this tweak is a good safety to prevent the behavior.
fixes https://github.com/istanbuljs/babel-plugin-istanbul/issues/94
CC: @speedskater
=> fix: don't instrument a file if it has already been instrumented

packages/istanbul-api/lib/config.js, packages/istanbul-api/lib/run-cover.js, packages/istanbul-api/test/config.test.js, packages/istanbul-api/test/run-check-coverage.test.js, packages/istanbul-api/test/run-cover.test.js, packages/istanbul-api/test/run-reports.test.js, packages/istanbul-api/test/sample-code/runInContext.js, packages/istanbul-lib-hook/lib/hook.js, packages/istanbul-lib-hook/test/hook.test.js, packages/istanbul-lib-hook/test/index.test.js
fix issue [#85](https://github.com/istanbuljs/istanbuljs/issues/85) along with [this pull request](https://github.com/istanbuljs/nyc/pull/680) to nyc
I feel kind of weak on the coverage of this change. Please give suggestions and comments so I can improve this pull request. Thank you. 
Ran
=> hook vm.runInContext

packages/istanbul-lib-instrument/src/visitor.js, packages/istanbul-lib-instrument/test/specs/classes.yaml, packages/istanbul-lib-instrument/test/util/guards.js, yarn.lock
@devsnek does this look reasonable?
fixes: https://github.com/istanbuljs/nyc/issues/685
=> fix: support conditional expression for superClass

packages/istanbul-lib-instrument/src/visitor.js, packages/istanbul-lib-instrument/test/specs/arrow-fn.yaml
=> fix: update instrument, account for lack of arrow expression (#119)

packages/test-exclude/index.js, packages/test-exclude/package.json
Fixes downstream vulnerability: https://snyk.io/vuln/npm:braces:20180219
=> upgrade micromatch

packages/istanbul-reports/lib/html/assets/base.css, packages/istanbul-reports/lib/html/assets/block-navigation.js, packages/istanbul-reports/lib/html/index.js, packages/istanbul-reports/lib/html/templates/foot.txt, packages/istanbul-reports/lib/html/templates/head.txt
=> feat: add uncovered block navigation

packages/istanbul-lib-instrument/src/visitor.js
=> Add a default value for `ignoreClassMethods`

packages/istanbul-reports/lib/html/helpers.js
See [the associated issue for details](https://github.com/istanbuljs/istanbuljs/issues/148).
=> Added named anchors to code coverage line numbers.

packages/istanbul-reports/lib/html/index.js
=> fix: ensure using correct context

packages/istanbul-api/lib/file-matcher.js, packages/istanbul-lib-coverage/lib/coverage-map.js, packages/istanbul-lib-coverage/lib/file.js, packages/istanbul-lib-report/lib/summarizer.js, packages/istanbul-lib-report/test/summarizer.test.js, packages/istanbul-lib-source-maps/lib/map-store.js, packages/istanbul-lib-source-maps/test/map-store.test.js
should fix https://github.com/istanbuljs/istanbuljs/issues/176
=> fix: use null prototype for map objects

packages/nyc-config-babel/package.json
=> chore(package): add files key to nyc-config-babel package

package-lock.json, packages/istanbul-lib-instrument/package.json, packages/istanbul-lib-report/package.json, packages/istanbul-lib-source-maps/package.json
Update all dependencies except source-map which requires node.js 8.
=> chore: Update dependencies.

packages/istanbul-lib-instrument/src/read-coverage.js
Comment "I think ?" does not add any valuable information.
=> JS: Remove unnecessary comment

packages/istanbul-api/lib/reporter.js, packages/istanbul-api/package.json, packages/istanbul-api/test/reporter.test.js
This pull request is an attempt to close the issue https://github.com/istanbuljs/nyc/issues/956.
=> Add support to exclude files on writing reports

.travis.yml
=> build: fix travis config

packages/test-exclude/test/test-exclude.js
Added test to ensure behavior doesn't accidentally change in the future.
=> chore: Add test for negated exclude of file that is not included.

packages/istanbul-lib-instrument/test/index.test.js
=> chore: Attempt to resolve Windows test timeout.

packages/test-exclude/index.js, packages/test-exclude/test/test-exclude.js
=> feat: Add common *.config.js dev configs to default exclude.

.eslintrc, .prettierignore, .travis.yml, README.md, greenkeeper.json, lerna.json, packages/istanbul-api/.doc.yml, packages/istanbul-api/README.md, packages/istanbul-lib-coverage/.doc.yml, packages/istanbul-lib-coverage/README.md, packages/istanbul-lib-hook/.doc.yml, packages/istanbul-lib-hook/README.md, packages/istanbul-lib-instrument/README.md, packages/istanbul-lib-instrument/api.md, packages/istanbul-lib-instrument/v0-changes.md, packages/istanbul-lib-report/.doc.yml, packages/istanbul-lib-report/README.md, packages/istanbul-lib-source-maps/.doc.yml, packages/istanbul-lib-source-maps/README.md, packages/istanbul-reports/.doc.yml, packages/istanbul-reports/README.md, packages/nyc-config-babel/README.md, packages/nyc-config-babel/index.json, packages/nyc-config-hook-run-in-this-context/README.md, packages/nyc-config-typescript/README.md, packages/test-exclude/README.md
prettier is configured but not run on every file.
So.. I'd suggest either adding filetypes to prettier ignore so they aren't formatted.. or format them.
I've gone with the latter on this PR.
=> Run all files through prettier

packages/test-exclude/README.md, packages/test-exclude/index.js, packages/test-exclude/package.json, packages/test-exclude/test/test-exclude.js
=> feat!: Remove configuration loading functionality

packages/istanbul-reports/test/cobertura-regression.js
This test throws an exception if run against `istanbul-report@2.2.5`.
=> chore: Add regression test for #384

packages/istanbul-lib-report/lib/report-base.js, packages/istanbul-reports/lib/html-spa/index.js
=> chore: Accept options object to ReportBase constructor

packages/istanbul-reports/lib/html-spa/src/getChildData.js
=> Fix #426 by filtering only exact paths

packages/istanbul-lib-coverage/package.json, packages/istanbul-lib-hook/package.json, packages/istanbul-lib-instrument/package.json, packages/istanbul-lib-report/package.json, packages/istanbul-lib-source-maps/package.json, packages/istanbul-reports/package.json, packages/nyc-config-babel/package.json, packages/nyc-config-hook-run-in-this-context/package.json, packages/nyc-config-typescript/package.json, packages/test-exclude/package.json
Ref https://docs.npmjs.com/files/package.json#repository
=> chore: Add repository.directory to package.json files

packages/istanbul-lib-instrument/src/default-opts.js, packages/istanbul-lib-instrument/src/index.js, packages/istanbul-lib-instrument/src/instrumenter.js, packages/istanbul-lib-instrument/src/read-coverage.js, packages/istanbul-lib-instrument/src/visitor.js, packages/istanbul-lib-instrument/test/already-instrumented.test.js, packages/istanbul-lib-instrument/test/util/verifier.js
=> fix: Populate lastFileCoverage for already instrumented files

packages/istanbul-reports/lib/html/assets/block-navigation.js, packages/istanbul-reports/lib/html/assets/sorter.js, packages/istanbul-reports/lib/html/index.js
=> feat: add filter to HTML report

packages/istanbul-lib-instrument/test/util/verifier.js
Fixes: https://github.com/istanbuljs/istanbuljs/issues/621
=> fix: globalThis with CSP compatibility

.github/workflows/ci.yml, .github/workflows/release-please.yml, README.md, packages/istanbul-lib-coverage/README.md, packages/istanbul-lib-hook/README.md, packages/istanbul-lib-instrument/README.md, packages/istanbul-lib-report/README.md, packages/istanbul-lib-source-maps/README.md, packages/istanbul-reports/README.md
Footwork to rename master to main.
=> build: rename master to main

README.md, packages/istanbul-lib-coverage/README.md, packages/istanbul-lib-hook/README.md, packages/istanbul-lib-report/README.md, packages/istanbul-reports/README.md
Greenkeeper service is EOL - https://greenkeeper.io
=> chore: Remove Greenkeeper badges

.github/workflows/release-please.yml
#773 did not work at all 😅 if this doesn't work, I'll rollback to the previous release
=> chore: attempt yet again to fix publish

.github/workflows/release-please.yml
=> chore: switch to non-deprecated GH action
